name = "CodeSnippets"
uuid = "c0d22ef6-76e5-4a28-a881-0f7c02be2ce0"
author = "Lukas Steinwender"
author_email = ""
credits = ""
maintainer = "Lukas Steinwender"
maintainer_email = ""
url = "https://github.com/TheRedElement/code_snippets"
version = "0.0.1"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.10.5"