author_email = ""
maintainer = "Lukas Steinwender"
name = "CodeSnippets"
author = "Lukas Steinwender"
credits = ""
last_changed = "2025-04-29"
version = "0.1.0"
description = "repository of some useful code snippets in various programming languages."
maintainer_email = ""
url = "https://github.com/TheRedElement/code_snippets"
uuid = "fc218cc1-83cc-44a0-9abf-5c55d920c5fe"

[compat]
julia = "1.10.5"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
