name = "CodeSnippets"
uuid = "fc218cc1-83cc-44a0-9abf-5c55d920c5fe"
author = "Lukas Steinwender"
author_email = ""
credits = ""
description = "repository of some useful code snippets in various programming languages."
last_changed = "2025-04-29"
maintainer = "Lukas Steinwender"
maintainer_email = ""
url = "https://github.com/TheRedElement/code_snippets"
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.10.5"
