[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src_py"]

[project]
name = "code_snippets"
version = "0.0.1"
authors = [
  { name="Lukas Steinwender", email="" },
]
description = "repository of some useful code snippets in various programming languages."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/TheRedElement/code_snippets"
Issues = "https://github.com/TheRedElement/code_snippets/issues"