author_email = ""
maintainer = "Lukas Steinwender"
name = "LuStCodeSnippets_jl"
author = "Lukas Steinwender"
credits = ""
last_changed = "2025-08-01"
version = "0.1.0"
description = "repository of some useful code snippets in various programming languages."
maintainer_email = ""
url = "https://github.com/TheRedElement/code_snippets"
uuid = "4e6fe0e1-735d-459e-81ef-de0b584a2e3c"

[compat]
julia = "1.10.5"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
PlotThemes = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
